spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          enabled: true
          routes:
            - id: chat-service
              uri: http://localhost:8092
              predicates:
                - Path=/chat-service/**
              filters:
                - RewritePath=/chat-service/(?<remaining>.*), /${remaining}
                - name: CircuitBreaker
                  args:
                    name: chat-service-resilience
                    fallbackUri: forward:/fallback
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 100
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 10
        permitted-number-of-calls-in-half-open-state: 5
    instances:
      chat-service-resilience:
        base-config: default

server:
  port: 8084

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
