spring:
  application:
    name: user-service
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    url: jdbc:mariadb://localhost:3306/zzapkaotalk
    user: admin
    password: 1234
    schemas: zzapkaotalk
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    host: localhost
    port: 3306
    username: admin
    password: 1234
    database: zzapkaotalk
    url: r2dbc:mariadb://localhost:3306/zzapkaotalk
  mail:
    jndi-name: mail/Session
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
      mail.transport.protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8090/realms/zzapkaotalk"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka
server:
  port: 8083
logging:
  level:
    org.springframework.security: TRACE
