spring:
  application:
    name: user-service
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    url: jdbc:mariadb://localhost:3306/zzapkaotalk
    user: admin
    password: 1234
    schemas: zzapkaotalk
    baseline-on-migrate: true
    baseline-version: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka
