spring:
  application:
    name: chat-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/zzapkaotalk/protocol/openid-connect/certs
          issuer-uri: http://localhost:8090/realms/zzapkaotalk
  kafka:
    bootstrap-servers: localhost:10001,localhost:10002,localhost:10003
    properties:
      schema.registry.url: http://localhost:8085
  datasource:
    host: localhost
    port: 3306
    username: admin
    password: 1234
    database: zzapkaotalk
    url: r2dbc:mariadb://localhost:3306/zzapkaotalk
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    url: jdbc:mariadb://localhost:3306/zzapkaotalk
    user: admin
    password: 1234
    schemas: zzapkaotalk
    baseline-on-migrate: true
    baseline-version: 1
    table: flyway_schema_history_chat_service
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  data:
    redis:
      port: 6379
      host: localhost
      lettuce:
        pool:
          max-active: 8
          enabled: true
  rsocket:
    server:
      transport: websocket
      port: 28079
      mapping-path: /rsocket
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8070/eureka
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8079
